# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conformance/peer/v1/peer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'conformance/peer/v1/peer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from be.v1 import limits_pb2 as be_dot_v1_dot_limits__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63onformance/peer/v1/peer.proto\x12\x13\x63onformance.peer.v1\x1a\x12\x62\x65/v1/limits.proto\"\x1f\n\x06\x46ilter\x12\x15\n\x07sku_ids\x18\x01 \x03(\tB\x04\xc8\xf3\x18\x02\"_\n\x0f\x42\x61tchGetRequest\x12\x11\n\x03ids\x18\x01 \x03(\tB\x04\xc8\xf3\x18\x03\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12+\n\x06\x66ilter\x18\x03 \x01(\x0b\x32\x1b.conformance.peer.v1.Filter\"\x12\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\"\xc1\x01\n\x10\x42\x61tchGetResponse\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.conformance.peer.v1.Item\x12N\n\rseen_metadata\x18\x02 \x03(\x0b\x32\x37.conformance.peer.v1.BatchGetResponse.SeenMetadataEntry\x1a\x33\n\x11SeenMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"7\n\x0eReserveRequest\x12\x17\n\x0fidempotency_key\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\"\xa7\x01\n\x0fReserveResponse\x12\x10\n\x08\x61ttempts\x18\x01 \x01(\x05\x12M\n\rseen_metadata\x18\x02 \x03(\x0b\x32\x36.conformance.peer.v1.ReserveResponse.SeenMetadataEntry\x1a\x33\n\x11SeenMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x9b\x02\n\x0bPeerService\x12\\\n\x08\x42\x61tchGet\x12$.conformance.peer.v1.BatchGetRequest\x1a%.conformance.peer.v1.BatchGetResponse\"\x03\x90\x02\x01\x12Y\n\x07Reserve\x12#.conformance.peer.v1.ReserveRequest\x1a$.conformance.peer.v1.ReserveResponse\"\x03\x90\x02\x02\x12S\n\x06Notify\x12#.conformance.peer.v1.ReserveRequest\x1a$.conformance.peer.v1.ReserveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conformance.peer.v1.peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILTER'].fields_by_name['sku_ids']._loaded_options = None
  _globals['_FILTER'].fields_by_name['sku_ids']._serialized_options = b'\310\363\030\002'
  _globals['_BATCHGETREQUEST'].fields_by_name['ids']._loaded_options = None
  _globals['_BATCHGETREQUEST'].fields_by_name['ids']._serialized_options = b'\310\363\030\003'
  _globals['_BATCHGETRESPONSE_SEENMETADATAENTRY']._loaded_options = None
  _globals['_BATCHGETRESPONSE_SEENMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_RESERVERESPONSE_SEENMETADATAENTRY']._loaded_options = None
  _globals['_RESERVERESPONSE_SEENMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_PEERSERVICE'].methods_by_name['BatchGet']._loaded_options = None
  _globals['_PEERSERVICE'].methods_by_name['BatchGet']._serialized_options = b'\220\002\001'
  _globals['_PEERSERVICE'].methods_by_name['Reserve']._loaded_options = None
  _globals['_PEERSERVICE'].methods_by_name['Reserve']._serialized_options = b'\220\002\002'
  _globals['_FILTER']._serialized_start=75
  _globals['_FILTER']._serialized_end=106
  _globals['_BATCHGETREQUEST']._serialized_start=108
  _globals['_BATCHGETREQUEST']._serialized_end=203
  _globals['_ITEM']._serialized_start=205
  _globals['_ITEM']._serialized_end=223
  _globals['_BATCHGETRESPONSE']._serialized_start=226
  _globals['_BATCHGETRESPONSE']._serialized_end=419
  _globals['_BATCHGETRESPONSE_SEENMETADATAENTRY']._serialized_start=368
  _globals['_BATCHGETRESPONSE_SEENMETADATAENTRY']._serialized_end=419
  _globals['_RESERVEREQUEST']._serialized_start=421
  _globals['_RESERVEREQUEST']._serialized_end=476
  _globals['_RESERVERESPONSE']._serialized_start=479
  _globals['_RESERVERESPONSE']._serialized_end=646
  _globals['_RESERVERESPONSE_SEENMETADATAENTRY']._serialized_start=368
  _globals['_RESERVERESPONSE_SEENMETADATAENTRY']._serialized_end=419
  _globals['_PEERSERVICE']._serialized_start=649
  _globals['_PEERSERVICE']._serialized_end=932
# @@protoc_insertion_point(module_scope)
