# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from conformance.peer.v1 import peer_pb2 as conformance_dot_peer_dot_v1_dot_peer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in conformance/peer/v1/peer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchGet = channel.unary_unary(
                '/conformance.peer.v1.PeerService/BatchGet',
                request_serializer=conformance_dot_peer_dot_v1_dot_peer__pb2.BatchGetRequest.SerializeToString,
                response_deserializer=conformance_dot_peer_dot_v1_dot_peer__pb2.BatchGetResponse.FromString,
                _registered_method=True)
        self.Reserve = channel.unary_unary(
                '/conformance.peer.v1.PeerService/Reserve',
                request_serializer=conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveRequest.SerializeToString,
                response_deserializer=conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveResponse.FromString,
                _registered_method=True)
        self.Notify = channel.unary_unary(
                '/conformance.peer.v1.PeerService/Notify',
                request_serializer=conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveRequest.SerializeToString,
                response_deserializer=conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveResponse.FromString,
                _registered_method=True)


class PeerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BatchGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reserve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchGet': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGet,
                    request_deserializer=conformance_dot_peer_dot_v1_dot_peer__pb2.BatchGetRequest.FromString,
                    response_serializer=conformance_dot_peer_dot_v1_dot_peer__pb2.BatchGetResponse.SerializeToString,
            ),
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveRequest.FromString,
                    response_serializer=conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveResponse.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveRequest.FromString,
                    response_serializer=conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conformance.peer.v1.PeerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conformance.peer.v1.PeerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BatchGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conformance.peer.v1.PeerService/BatchGet',
            conformance_dot_peer_dot_v1_dot_peer__pb2.BatchGetRequest.SerializeToString,
            conformance_dot_peer_dot_v1_dot_peer__pb2.BatchGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conformance.peer.v1.PeerService/Reserve',
            conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveRequest.SerializeToString,
            conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conformance.peer.v1.PeerService/Notify',
            conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveRequest.SerializeToString,
            conformance_dot_peer_dot_v1_dot_peer__pb2.ReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
