"""Identifiers (be-protocol P11.5): UUIDv7 generated by the application, canonical lower-case text."""

from __future__ import annotations

import re
import uuid
from datetime import datetime, timezone

from besdk.errors import ProtocolError

_ID_RE = re.compile(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}")


def new_id() -> uuid.UUID:
    """A new UUIDv7 (RFC 9562; the standard library's on CPython ≥ 3.14)."""
    return uuid.uuid7()


def parse_id(text: str) -> uuid.UUID:
    """Strict: 36 characters with hyphens, version 7, variant 10xx; upper case is normalised."""
    if not isinstance(text, str) or not _ID_RE.fullmatch(text):
        raise ProtocolError("ID_INVALID", repr(text))
    return uuid.UUID(text)


def id_unix_ms(u: uuid.UUID) -> int:
    return u.int >> 80


def id_time(u: uuid.UUID) -> datetime:
    """The instant embedded in a UUIDv7 (= ``created_at`` of a partitioned row)."""
    ms = id_unix_ms(u)
    return datetime.fromtimestamp(ms // 1000, timezone.utc).replace(microsecond=(ms % 1000) * 1000)


def rfc3339_ms(t: datetime) -> str:
    """RFC 3339 UTC with milliseconds, omitted when zero."""
    t = t.astimezone(timezone.utc)
    s = t.strftime("%Y-%m-%dT%H:%M:%S")
    ms = t.microsecond // 1000
    return f"{s}.{ms:03d}Z" if ms else f"{s}Z"
